### ISSUE TITLE
Drawer right padding in tvOS simulator

### ISSUE THREAD

**Issue by giolaq** [AmazonAppDev/react-native-multi-tv-app-sample#24]
**Describe the bug**
While running the app on the tvOS simulator the drawer has a right side padding ( see the picture attached, it's the light blu padding on the right side of the drawer )

**Screenshots**
![tvOSSim](https://github.com/user-attachments/assets/fb85c14a-b8c9-45bf-a431-d59b0e2b16af)

**To Reproduce**
Run the app on the tvOS simulator with ```npx expo run:ios```

**Expected behavior**
The drawer should not have any white padding on the right side, like in Android TV, Fire TV and Web.
In the attached screenshot the right behavior 
![Screenshot_1729281248](https://github.com/user-attachments/assets/b3b40e41-6677-43f8-a302-1eaf8949c072)

**Comment by EspeonIV** [comment]
Hey @giolaq, can you assign this to me?

**Comment by giolaq** [comment]
Assigned! Thank you!

**Comment by EspeonIV** [comment]
Macbook is hating me, sorry for wasting your time.
