### ISSUE TITLE
Nav to drawer does not work in the Explore tab on Apple TV

### ISSUE THREAD

**Issue by douglowder** [AmazonAppDev/react-native-multi-tv-app-sample#3]
Steps to reproduce:

- Follow README steps to install and run the app on TV simulator
- Navigate to "Explore" tab
- Swipe or tap left to open the drawer

Expected behavior:

- Drawer should open

Actual behavior:

- Drawer does not open
- If you swipe or tap right, and THEN swipe or tap left, the drawer does open

Not sure if this is an issue with the state management of the drawer in the app, or an issue in `react-tv-space-navigation`.
If you add a call to `useTVEventHandler` that calls `onDirectionHandledWithoutMovement()` when eventType=left, the issue is fixed.

**Comment by giolaq** [comment]
thank you for reporting. I've found the state of the drawer was not correctly set up when navigating in the screen.
I've merged a fix.

**Comment by douglowder** [comment]
Thanks @giolaq 😃
