### ISSUE TITLE
tvos issue when running on apple tv, the navigation is not working, moving left right up down not working

### ISSUE THREAD

**Issue by cabikhalil-softimpact** [AmazonAppDev/react-native-multi-tv-app-sample#39]
tvos issue when running on apple tv, the navigation is not working, moving left right up down not working

**Comment by giolaq** [comment]
are you using the controller? Any info about your simulator or tvOS version used?

**Comment by giolaq** [comment]
I've fixed it adding the 4 events of swipe of tvOS controller
